from __future__ import annotations

from typing import Protocol

from telegram_media_bot.domain.audit import (
    AuditDeliveryResult,
    AuditEvent,
    DestinationProbeResult,
    LoggerDestination,
    LoggerDestinationHealth,
    LoggerHealthSnapshot,
    LoggerOutboxItem,
    TelegramSourceReference,
)


class AuditRepository(Protocol):
    def initialize(self) -> None: ...
    def reconcile_config(self, chat_ids: tuple[int, ...]) -> None: ...
    def list_destinations(self) -> tuple[LoggerDestination, ...]: ...
    def add_runtime_destination(self, chat_id: int) -> LoggerDestination: ...
    def remove_runtime_destination(self, chat_id: int) -> bool: ...
    def set_destination_enabled(self, chat_id: int, enabled: bool) -> LoggerDestination: ...
    def record_probe_health(
        self, chat_id: int, health: LoggerDestinationHealth, failure_class: str | None = None
    ) -> LoggerDestination | None: ...
    def enqueue(self, event: AuditEvent) -> int: ...
    def prepare_delivery_output(self, job_id: str) -> bool: ...
    def delivery_output_pending(self, job_id: str) -> bool: ...
    def pending_delivery_outputs(self, *, limit: int = 50) -> tuple[str, ...]: ...
    def complete_delivery_output(self, job_id: str) -> bool: ...
    def extend_submission_source(self, source: TelegramSourceReference) -> int: ...
    # Deprecated since v1.4.0-rc.2: per-user privacy acknowledgement is no
    # longer consulted by the acceptance path; kept for schema compatibility.
    def has_privacy_acknowledgement(self, user_id: int, policy_version: str) -> bool: ...
    def acknowledge_privacy(self, user_id: int, policy_version: str) -> bool: ...
    def recover_expired_leases(self) -> tuple[int, int]: ...
    def claim_pending(self, *, limit: int = 20) -> tuple[LoggerOutboxItem, ...]: ...
    def mark_send_started(self, item: LoggerOutboxItem) -> bool: ...
    def mark_succeeded(self, item: LoggerOutboxItem) -> None: ...
    def mark_retryable(self, item: LoggerOutboxItem, failure_class: str) -> None: ...
    def mark_uncertain(self, item: LoggerOutboxItem, failure_class: str) -> None: ...
    def mark_terminal(self, item: LoggerOutboxItem, failure_class: str) -> None: ...
    def health_snapshot(self) -> LoggerHealthSnapshot: ...


class AuditDeliveryPort(Protocol):
    async def deliver(self, item: LoggerOutboxItem) -> AuditDeliveryResult: ...


class LoggerDestinationVerifier(Protocol):
    """Probe a Telegram channel and prove bot posting permission (T028)."""

    async def probe(self, chat_id: int) -> DestinationProbeResult: ...


class TelegramSourceResolver(Protocol):
    """Resolve bounded, already-durable source identities for a Telegram album."""

    def media_group_message_ids(self, chat_id: int, media_group_id: str) -> tuple[int, ...]: ...


__all__ = [
    "AuditDeliveryPort",
    "AuditRepository",
    "LoggerDestinationVerifier",
    "TelegramSourceResolver",
]
