from __future__ import annotations

from typing import Protocol

from telegram_media_bot.domain.audit import (
    AuditDeliveryResult,
    AuditEvent,
    DestinationProbeResult,
    LoggerDestination,
    LoggerDestinationHealth,
    LoggerHealthSnapshot,
    LoggerOutboxItem,
)


class AuditRepository(Protocol):
    def initialize(self) -> None: ...
    def reconcile_config(self, chat_ids: tuple[int, ...]) -> None: ...
    def list_destinations(self) -> tuple[LoggerDestination, ...]: ...
    def add_runtime_destination(self, chat_id: int) -> LoggerDestination: ...
    def remove_runtime_destination(self, chat_id: int) -> bool: ...
    def set_destination_enabled(self, chat_id: int, enabled: bool) -> LoggerDestination: ...
    def record_probe_health(
        self, chat_id: int, health: LoggerDestinationHealth, failure_class: str | None = None
    ) -> LoggerDestination | None: ...
    def enqueue(self, event: AuditEvent) -> int: ...
    def recover_expired_leases(self) -> tuple[int, int]: ...
    def claim_pending(self, *, limit: int = 20) -> tuple[LoggerOutboxItem, ...]: ...
    def mark_send_started(self, item: LoggerOutboxItem) -> bool: ...
    def mark_succeeded(self, item: LoggerOutboxItem) -> None: ...
    def mark_retryable(self, item: LoggerOutboxItem, failure_class: str) -> None: ...
    def mark_uncertain(self, item: LoggerOutboxItem, failure_class: str) -> None: ...
    def mark_terminal(self, item: LoggerOutboxItem, failure_class: str) -> None: ...
    def health_snapshot(self) -> LoggerHealthSnapshot: ...


class AuditDeliveryPort(Protocol):
    async def deliver(self, item: LoggerOutboxItem) -> AuditDeliveryResult: ...


class LoggerDestinationVerifier(Protocol):
    """Probe a Telegram channel and prove bot posting permission (T028)."""

    async def probe(self, chat_id: int) -> DestinationProbeResult: ...


__all__ = ["AuditDeliveryPort", "AuditRepository", "LoggerDestinationVerifier"]
